services:
  ip-manager:
    image: danielndias/ip-manager:latest
    container_name: ip-manager
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - ./data:/data
    environment:
      - SECRET_KEY=change-me-in-production
